## Adapted from Libero sample configuration.
## https://github.com/libero/sample-configuration/blob/master/.travis.yml
sudo: required

language: minimal

services: docker

before_install:
  - docker -v
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  # @todo change the name of env, add to ignore and add copy to init.
  # - cp .env.dist .env

install:
  - travis_retry docker-compose pull
  # Add any database test fixtures to `database/sql` before madoc init-ci.
  - ./bin/madoc init-ci

before_script:
  - ./bin/madoc start
  - ./.travis/wait-for-omeka.sh

script:
  - .travis/test-script.sh

after_script:
  - ./bin/madoc stop


## Docker caching
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  bundler: true
  directories:
    - $HOME/docker

#if: |
#  branch = master OR \
#  type = pull_request
